#-----------------------------------------
# Backend Build Server Image
#-----------------------------------------

FROM maven:3.9.4-eclipse-temurin-17-focal

# Install ansible
RUN apt update 
RUN apt install -y software-properties-common 
RUN add-apt-repository --yes --update ppa:ansible/ansible 
RUN apt install ansible -y