#-----------------------------------------
# Frontend Build Server Image
#-----------------------------------------

FROM node:20

# Install ansible
RUN echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu focal main" >> /etc/apt/sources.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
RUN apt update
RUN apt install ansible -y

# Install zip
RUN apt install zip -y