#-----------------------------------------
# Frontend Build Server Image
#-----------------------------------------

FROM node:20

# Install Python and Pipx
RUN apt update
RUN apt install python3 -y
RUN apt install python3-pip -y
RUN python3 -m pip install --user pipx --break-system-packages
RUN python3 -m pipx ensurepath
RUN apt install python3.11-venv -y

# Install zip
RUN apt install zip -y

# Install Ansible
RUN python3 -m pipx install --include-deps ansible